name: parking_shared
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  shelf: ^1.4.0
  intl: ^0.18.0
  glowy_borders: ^1.0.2
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  replay_bloc: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
