name: serverparking_shared
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.0
  firebase_dart: ^1.2.2

dev_dependencies:
  build_runner: ^2.4.13
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
