name: parking_user
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  parking_shared:
    path: ../parking_shared
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  glowy_borders: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true