name: parking_user
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  http: ^1.2.2
  flutter:
    sdk: flutter
  parking_shared:
    path: ../parking_shared
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_auth: ^5.4.1
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  glowy_borders: ^1.0.2
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  equatable: ^2.0.7
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  replay_bloc: ^0.2.7
  flutter_local_notifications: ^18.0.1
  uuid: ^4.5.1
  timezone: ^0.10.0
  flutter_timezone: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true