// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMNtpGvo3wsmniE1ojQdjhBYVHEV7lbRc',
    appId: '1:1059671592375:web:26f9cee34fda694784ec32',
    messagingSenderId: '1059671592375',
    projectId: 'serverparking-9de55',
    authDomain: 'serverparking-9de55.firebaseapp.com',
    databaseURL: 'https://serverparking-9de55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serverparking-9de55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGwyn8QYsmxlT7qW3GltoGemRVQaFrgE',
    appId: '1:1059671592375:android:4e383264b3d3827984ec32',
    messagingSenderId: '1059671592375',
    projectId: 'serverparking-9de55',
    databaseURL: 'https://serverparking-9de55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serverparking-9de55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0oCS2HMVb4ahIanQ6xh-HD3y4G3fvKU',
    appId: '1:1059671592375:ios:3132e2efd5d8476c84ec32',
    messagingSenderId: '1059671592375',
    projectId: 'serverparking-9de55',
    databaseURL: 'https://serverparking-9de55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serverparking-9de55.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy0oCS2HMVb4ahIanQ6xh-HD3y4G3fvKU',
    appId: '1:1059671592375:ios:3132e2efd5d8476c84ec32',
    messagingSenderId: '1059671592375',
    projectId: 'serverparking-9de55',
    databaseURL: 'https://serverparking-9de55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'serverparking-9de55.firebasestorage.app',
    iosBundleId: 'com.example.parking',
  );
}
